name: Example report - fork

on:
  workflow_dispatch:
    inputs:
      fork:
        description: 'Fork to target'
        required: true
        type: string
      branch:
        description: 'Branch to target'
        required: true
        type: string

env:
  PER_PAGE: 20

jobs:
  get-environment:
    name: Get Environment
    runs-on: ubuntu-latest
    outputs:
      per_page: ${{ env.PER_PAGE }}
      gitref: ${{ steps.env.outputs.gitref }}
      date: ${{ steps.env.outputs.date }}
      pixeleagle_project: ${{ steps.env.outputs.pixeleagle_project }}
    steps:
      - name: Checkout Bevy main branch
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.fork }}
          ref: ${{ inputs.branch }}
      - name: Get Environment
        id: env
        run: |
          echo "gitref=`git rev-parse HEAD`" >> $GITHUB_OUTPUT
          echo "date=`date +%Y%m%d%H%M`" >> $GITHUB_OUTPUT
          echo "pixeleagle_project=B25A040A-A980-4602-B90C-D480AB84076D" >> $GITHUB_OUTPUT

  native-run:
    needs: [get-environment]
    uses: ./.github/workflows/workflow-native.yml
    with:
      gitref: ${{ needs.get-environment.outputs.gitref }}
      pixeleagle_project: ${{ needs.get-environment.outputs.pixeleagle_project }}
      branch: "${{ inputs.fork }} - ${{ inputs.branch }}"
      repository: ${{ inputs.fork }}
      per_page: "${{ needs.get-environment.outputs.per_page }}"
    secrets: inherit

  mobile-run:
    needs: [get-environment]
    uses: ./.github/workflows/workflow-mobile.yml
    with:
      gitref: ${{ needs.get-environment.outputs.gitref }}
      pixeleagle_project: ${{ needs.get-environment.outputs.pixeleagle_project }}
      branch: "${{ inputs.fork }} - ${{ inputs.branch }}"
      repository: ${{ inputs.fork }}
    secrets: inherit

  wasm-run:
    needs: [get-environment]
    uses: ./.github/workflows/workflow-wasm.yml
    with:
      gitref: ${{ needs.get-environment.outputs.gitref }}
      pixeleagle_project: ${{ needs.get-environment.outputs.pixeleagle_project }}
      branch: "${{ inputs.fork }} - ${{ inputs.branch }}"
      repository: ${{ inputs.fork }}
    secrets: inherit
